import fs from "fs";
import path from "path";
import dotenv from "dotenv";
import { knex as createKnex } from "knex";
import {
  crossPlaneRefs,
  type CrossPlaneRef,
} from "../database/cross-plane-refs";
import {
  coreMigrationConnection,
  localOnlyRefusal,
  migrationsDirectory,
} from "../database/migration-sets";
import {
  coreHistoryMismatch,
  type SourceDatabase,
} from "./generate-tenant-baseline";

/**
 * Writes `src/database/cross-plane-refs.generated.ts` (db-per-company T12a,
 * scope B):
 *
 *   npx ts-node src/scripts/generate-cross-plane-refs.ts [--check]
 *
 * Source: the catalogue (`crossPlaneRefs`) of the LOCAL database named by
 * SQL_DATABASE, whose `knex_migrations` must name exactly the files in
 * `migrations/core/` (same refusal as `generate-tenant-baseline.ts`).
 *
 * Read once here while both planes still share a database, because once a
 * tenant's tables live in their own database that database's catalogue no
 * longer holds these constraints to discover — the tenant baseline generator
 * strips them (`generate-tenant-baseline.ts`'s `withoutCrossPlaneForeignKeys`).
 * `purgeUser` and `db-check-integrity` read the committed output of this
 * generator instead of querying any one target's catalogue at run time; the
 * module manifests' declared user references need no such capture, since
 * they are already static code (`modules/registry.ts`'s
 * `declaredUserReferences`) with nothing to read from a database.
 *
 * `--check` compares instead of writing and exits 1 on any difference.
 */

export const generatedFilePath = (): string =>
  path.join(__dirname, "..", "database", "cross-plane-refs.generated.ts");

const renderRef = (ref: CrossPlaneRef): string =>
  [
    "  {",
    `    constraintName: ${JSON.stringify(ref.constraintName)},`,
    `    table: ${JSON.stringify(ref.table)},`,
    `    column: ${JSON.stringify(ref.column)},`,
    `    referencedTable: ${JSON.stringify(ref.referencedTable)},`,
    `    referencedColumn: ${JSON.stringify(ref.referencedColumn)},`,
    `    deleteRule: ${JSON.stringify(ref.deleteRule)},`,
    `    nullable: ${String(ref.nullable)},`,
    "  }",
  ].join("\n");

export function renderCrossPlaneRefs(refs: readonly CrossPlaneRef[]): string {
  return [
    'import type { CrossPlaneRef } from "./cross-plane-refs";',
    "",
    "/**",
    " * GENERATED by `src/scripts/generate-cross-plane-refs.ts`. Never edit it by",
    " * hand: regenerate, and `git diff` must then be empty.",
    " *",
    " * Every foreign key from a tenant table to a central-only table, captured",
    " * once from a `db:bootstrap`-built core database while both planes still",
    " * shared it (db-per-company T12a). `purgeUser` and `db-check-integrity`",
    " * read this list instead of querying the catalogue at run time: once a",
    " * tenant's tables live in their own database, its catalogue no longer",
    " * holds these constraints to discover — the tenant baseline generator",
    " * dropped them.",
    " */",
    "export const GENERATED_CROSS_PLANE_REFS: readonly CrossPlaneRef[] = [",
    refs.map(renderRef).join(",\n"),
    refs.length > 0 ? "," : "",
    "];",
    "",
  ].join("\n");
}

export type GenerateCrossPlaneRefsDeps = {
  env: NodeJS.ProcessEnv;
  openSource: () => SourceDatabase;
  coreMigrationFiles: () => string[];
  crossPlaneRefsOf: (source: SourceDatabase) => Promise<CrossPlaneRef[]>;
  outputFile: string;
  out: (line: string) => void;
  err: (line: string) => void;
};

export const generateCrossPlaneRefsDeps = (
  env: NodeJS.ProcessEnv,
): GenerateCrossPlaneRefsDeps => ({
  env,
  openSource: () => {
    const connection = coreMigrationConnection();
    return {
      connection,
      knex: createKnex({ client: "pg", connection, pool: { min: 0, max: 1 } }),
    };
  },
  coreMigrationFiles: () =>
    fs
      .readdirSync(migrationsDirectory("core"))
      .filter((name) => name.endsWith(".ts")),
  crossPlaneRefsOf: ({ knex }) => crossPlaneRefs(knex),
  outputFile: generatedFilePath(),
  out: console.log,
  err: console.error,
});

export async function runGenerateCrossPlaneRefs(
  argv: readonly string[],
  deps: GenerateCrossPlaneRefsDeps,
): Promise<number> {
  const refusal = localOnlyRefusal("generate-cross-plane-refs", deps.env);
  if (refusal !== undefined) {
    deps.err(refusal);
    return 1;
  }
  const unknown = argv.find((arg) => arg !== "--check");
  if (unknown !== undefined) {
    deps.err(
      `generate-cross-plane-refs: unknown argument ${unknown}\n` +
        "usage: generate-cross-plane-refs [--check]",
    );
    return 2;
  }
  let source: SourceDatabase | undefined;
  try {
    source = deps.openSource();
    const applied = (await source.knex.raw(
      "select name from knex_migrations",
    )) as { rows: { name: string }[] };
    const mismatch = coreHistoryMismatch(
      applied.rows.map((row) => row.name),
      deps.coreMigrationFiles(),
    );
    if (mismatch !== undefined) {
      deps.err(`generate-cross-plane-refs: refused: ${mismatch}`);
      return 1;
    }
    const refs = await deps.crossPlaneRefsOf(source);
    const rendered = renderCrossPlaneRefs(refs);
    const file = deps.outputFile;
    if (argv.includes("--check")) {
      const committed = fs.existsSync(file)
        ? fs.readFileSync(file, "utf8")
        : "";
      if (committed !== rendered) {
        deps.err(`${file} differs from a fresh render: regenerate it`);
        return 1;
      }
      deps.out(`${file} is current`);
      return 0;
    }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, rendered);
    deps.out(`wrote ${file}`);
    return 0;
  } catch (error) {
    deps.err(
      `generate-cross-plane-refs: ${error instanceof Error ? error.message : String(error)}`,
    );
    return 1;
  } finally {
    await source?.knex.destroy();
  }
}

if (require.main === module) {
  dotenv.config();
  void runGenerateCrossPlaneRefs(
    process.argv.slice(2),
    generateCrossPlaneRefsDeps(process.env),
  ).then((code) => {
    process.exitCode = code;
  });
}
